/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs345.deadwood;

import java.util.*;
import java.awt.event.*;
public class Deadwood {
    
    public static void main(String[] args) {
        BoardView boardView = new BoardView();
        ArrayList<Player> players = new ArrayList<Player>();
        ArrayList<Scene> scenes = new ArrayList<Scene>();
        HashMap<String, Location> locations = new HashMap<String, Location>();

        parsingXML parser = new parsingXML();

        parser.parseBoard(locations);
        parser.parseCards(scenes);

        Collections.shuffle(scenes);

        int iter = 0;
        for(String key : locations.keySet()) {
            Location currentLoc = locations.get(key);
            currentLoc.setScene(scenes.get(iter++));
            // boardView.renderLocation(currentLoc);
        }

        LaunchPage launchPage = new LaunchPage(players, boardView, locations);

        
    }
}