/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs345.deadwood;

import java.util.*;
import java.awt.event.*;
import java.io.InputStream;

public class Deadwood {

 
    
    public static void main(String[] args) throws Exception{
        BoardView boardView = new BoardView();



        ArrayList<Player> players = new ArrayList<Player>();
        ArrayList<Scene> scenes = new ArrayList<Scene>();
        Player currentPlayer;
        HashMap<String, Location> locations = new HashMap<String, Location>();
        Integer days;

        parsingXML parser = new parsingXML();

        parser.parseBoard(locations);
        parser.parseCards(scenes);

        Collections.shuffle(scenes);

        int iter = 0;
        for(String key : locations.keySet()) {
            Location currentLoc = locations.get(key);
            currentLoc.setScene(scenes.get(iter++));
        }

        LaunchPage launchPage = new LaunchPage(players, boardView, locations);
        days = players.size() <= 3 ? 3 : 4;
        currentPlayer = players.get(0);
        
        
        System.out.println(currentPlayer.getPlayer());

    }
}